/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Consultas.java
 *
 * Created on 20/10/2011, 16:50:06
 */
package br.com.fzlbpms.Fluxo.Janelas;

import br.com.fzlbpms.Fluxo.BancoDeDados.OperacaoBD;
import br.com.fzlbpms.Fluxo.Logicas.SolicitacaoEspaco;
import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Consultas extends javax.swing.JDialog {
 JMonthChooser jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
 JYearChooser jYearChooser = new com.toedter.calendar.JYearChooser();
    /** Creates new form Consultas */
    public Consultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jrbTodas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta à Agenda de Fluxo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Local", "Atividade", "Executor", "Horario", "Alimentação", "Participantes", "Equipamentos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS OS LOCAIS", "SALA 1", "SALA 2", "ANFITEATRO", "EXTERNO", "LANCHONETE - EVENTOS", "LANCHONETE - JOGOS", "LANCHONETE - DANÇAS" }));

        jLabel1.setText("Local");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("logo_ipgg2.gif"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("Índice1_1.jpeg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("SECRETARIA DE ESTADO DA SAÚDE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("INSTITUTO PAULISTA DE GERIATRIA E GERONTOLOGIA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("\"JOSÉ ERMÍRIO DE MORAES\"");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DIRETORIA TÉCNICA");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Com Alimentação");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Com Equipamento");

        buttonGroup1.add(jrbTodas);
        jrbTodas.setSelected(true);
        jrbTodas.setText("Todas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(195, 195, 195)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jrbTodas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel8))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbTodas)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1116, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling cojMonthChooser1de here:
            OperacaoBD bd = new OperacaoBD();
            List<SolicitacaoEspaco> s = new ArrayList<SolicitacaoEspaco>();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int linhas = dtm.getRowCount();
            boolean comAlimentacao = jRadioButton2.isSelected();
            boolean comEquipamento = jRadioButton3.isSelected();
            if ((comAlimentacao == false) && (comEquipamento == false)){
                comAlimentacao = comEquipamento = true;
            }
            s = bd.getSolicitacoesPorMes(
                    jMonthChooser1.getMonth() + 1, jYearChooser.getYear(), jComboBox1.getSelectedItem() + "",comAlimentacao,comEquipamento);
            int i;
            if (dtm.getRowCount() > 0) {
                for (i = 0; i < linhas; i++) {
                    dtm.removeRow(0);
                }
            }
            if (!s.isEmpty()) {



                /*DefaultTableCellRenderer centraliza = new DefaultTableCellRenderer() {
                public void setValue(Object value) {
                setHorizontalAlignment(JLabel.CENTER);                    
                super.setValue(value);
                }
                };
                
                jTable1.getColumn("Data").setCellRenderer(centraliza);
                jTable1.getColumn("Hora do Início").setCellRenderer(centraliza);
                jTable1.getColumn("Hora do Fim").setCellRenderer(centraliza);
                jTable1.getColumn("Cardápios").setCellRenderer(centraliza);
                 */
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                for (i = 0; i < s.size(); i++) {
                    String data = df.format(s.get(i).getDataAtividade());
                    String horaIni = s.get(i).getHoraAtividade() + "";
                    String horaFim = s.get(i).getHoraTermino() + "";
                    String cardapios = "";
                    String horaAlim = "";
                    String executor = s.get(i).getExecutorAtividade();
                    String numeroParticipantes = s.get(i).getNumeroParticipantes()+"";
                    String nomeAtiv = s.get(i).getNomeAtividade();
                    String equipamentos = "";
                    String local = s.get(i).getLocalSolicitado();
                    
                    if (s.get(i).isCard1() || s.get(i).isCard2() || s.get(i).isCard3()
                            || s.get(i).isCard4() || s.get(i).isCard5() || s.get(i).isCard6()) {
                        horaAlim += s.get(i).getHoraAlimentacao() + "";
                    }
                    
                    if (s.get(i).isCard1()) {
                        cardapios += " Nº1";
                    }
                    if (s.get(i).isCard2()) {
                        cardapios += " Nº2";
                    }
                    if (s.get(i).isCard3()) {
                        cardapios += " Nº3";
                    }
                    if (s.get(i).isCard4()) {
                        cardapios += " Nº4";
                    }
                    if (s.get(i).isCard5()) {
                        cardapios += " Nº5";
                    }
                    if (s.get(i).isCard6()) {
                        cardapios += " Nº6";
                    }
                    
                    if (s.get(i).isCaixasSom()) {
                        equipamentos += "Caixas de Som ";
                    }
                    if (s.get(i).isDVD()) {
                        equipamentos += "DVD ";
                    }
                    if (s.get(i).isDataShow()) {
                        equipamentos += "DataShow ";
                    }
                    if (s.get(i).isFilmar()) {
                        equipamentos += "Filmar ";
                    }
                    if (s.get(i).isFotografar()) {
                        equipamentos += "Fotografar ";
                    }
                    if (s.get(i).isMesaSom()) {
                        equipamentos += "Mesa de Som ";
                    }
                    if (s.get(i).isMicrofone()) {
                        equipamentos += "Microfone ";
                    }
                    if (s.get(i).isNotebook()) {
                        equipamentos += "Notebook ";
                    }
                    if (s.get(i).isTelevisao()) {
                        equipamentos += "Televisao ";
                    }
                    if (s.get(i).isVideoCassete()) {
                        equipamentos += "Videocassete ";
                    }
                    dtm.addRow(new String[]{data, local, nomeAtiv, executor, horaIni + " - " +horaFim,
                    cardapios + " - "+horaAlim, numeroParticipantes,equipamentos});
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não há eventos agendados para o mês selecionado com estas carcterísticas");
            }
        } catch (Exception ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
        javax.swing.UIManager.setLookAndFeel(info.getClassName());
        break;
        }
        }
        } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Consultas dialog = new Consultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrbTodas;
    // End of variables declaration//GEN-END:variables
}
